@startuml moz_database
skinparam {
    Nodesep 150
    Ranksep 200
    Linetype ortho
}

skinparam entity {
    BackgroundColor LightBlue
    FontSize 14
    ArrowThickness 1
}

entity year {
    + Id: serial [pk]
    --
    + name: integer
    + head_of_state: text
}

entity country_data {
    + Id: serial [pk]
    --
    + area_in_sqkm: integer
    + capital_city: text
    + official_language: text
    + independence_date: date
}

entity provinces {
   + id: serial [pk]
   --
   + province_name: text
   + area_in_sqkm: integer
   + population_density: integer
   --
   + year_id: integer [FK] references year(id)
}

entity population_per_thousand{
    + id: serial [pk]
    --
    + total: numeric(7,1)
    + male_population: numeric(7,1)
    + female_population: numeric (7,1)
    --
    + province_id: integer [FK] references provinces(id)
}

entity population_percentual_structure {
    + id: serial [pk]
    + total: numeric (4, 1)
    + male_population: numeric (4, 1)
    + female_population: numeric (4, 1)
    --
    + province_id: integer [FK] references provinces(id)
}


entity country_pop_indicators {
    + id: serial [pk]
    --
    + total: numeric(7, 1)
    + male: numeric(7, 1)
    + female: numeric(6, 1)
    + urban_percentual: numeric (3,1)
    + sex_ratio: numeric(3,1)
    + gross_mortality_rate: numeric (4, 1)
    + gross_birth_rate: numeric (3, 1)
    + growth_rate: numeric (4, 1)
    --
    + year_id: integer [FK] references year(id)
}

entity dependency_rate {
    + year_id: integer [PK] references year(id)
    --
    + total: numeric (3,1)
    + young: numeric (3,1)
}

entity life_expectancy_at_birth {
    + year_id: integer [PK] references year(id)
    --
    + average_life_expectancy: numeric (3,1)
    + male_life_expectancy: numeric (3,1)
    + female_life_expectancy: numeric (3,1)
}

entity infant_mortality {
    + year_id: integer [PK] referenceces year(id)
    --
    + average_infant_mortality: numeric (3, 1)
    + male_infant_mortality: numeric (3, 1)
    + female_infant_mortality: numeric (3, 1) 
}

'relashionships:
year --{ provinces
provinces --{ population_per_thousand
provinces --{ population_percentual_structure
year -- life_expectancy_at_birth
year --{ country_pop_indicators
year -- dependency_rate
year -- infant_mortality

@enduml
