@startuml moz_database
skinparam {
    Nodesep 80
    Ranksep 80
    Linetype ortho
}

skinparam entity {
    BackgroundColor LightBlue
    FontSize 14
    ArrowThickness 1
}

entity year {
    + Id: serial [pk]
    --
    + name: integer
    + head_of_state: text
}

entity country_data {
    + Id: serial [pk]
    --
    + area_in_sqkm: integer
    + capital_city: text
    + official_language: text
    + independence_date: date
    --
    + year_id: integer [FK] references year(id)
}

entity provinces {
   + id: serial [pk]
   --
   + province_name: text
   + area_in_sqkm: integer
   + population_density: integer
   --
   + country_data_id: integer [FK] references country_data(id)
   + year_id: integer [FK] references year(id)
}

entity population_per_thousand{
    + id: serial [pk]
    --
    + total: integer
    + male_population: integer
    + female_population: integer
    --
    + province_id: integer [FK] references provinces(id)
}

entity population_percentual_structure {
    + id: serial [pk]
    + total: integer
    + male_population: integer
    +female_population: integer
    --
    + province_id: integer [FK] references provinces(id)
}


entity country_pop_indicators {
    + id: serial [pk]
    --
    + total: integer
    + male: integer
    + female: integer
    + urban_percentual: numeric (4, 1)
    + sex_ratio: integer
    + gross_mortality_rate: numeric (4, 1)
    + gross_birth_rate: numeric (4, 1)
    + growth_rate: numeric (4, 1)
    --
    + year_id: integer [FK] references year(id)
}

entity dependency_rate {
    + id: serial [pk]
    --
    + total: numeric (4, 1)
    + young: numeric (4, 1)
    --
    + year_id: integer [FK] references year(id)
}

entity life_expectancy {
    + year_id: integer [PK] references year(id)
    --
    + male: numeric (4, 1)
    + female: numeric (4, 1)
}

'relashionships:

year  --{ country_data
country_data --{ provinces
provinces --{ population_per_thousand
provinces --{ population_percentual_structure
year -- life_expectancy
year --{ country_pop_indicators
year -- dependency_rate



@enduml
